version: '3'
services:
  app:
    image: dalsam/runners-high_first
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" #8080 노출 in:out
    environment:
      - SPRING_PROFILES_ACTIVE=docker #docker 프로파일 활성화
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - backend
  postgresql:
    image: postgres:17
    ports:
    - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: runners_high_db
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres: